.\" This manpage is copyright (C) 2012 Yuandong Liang<yl20e11@ecs.soton.ac.uk>.

.TH cw1-6005-yl20e11 8 "February 23, 2012" "Linux"
.SH NAME
rssReader \- Wrapper for /usr/share/cw1-6005-yl20e11/index.php
.SH SYNOPSIS
.B rssReader
.SH DESCRIPTION
Calling rssReader runs php on /usr/share/cw1-6005-yl20e11/index.php.

.SH AUTHOR
cw1-6005-yl20e11 was written by Yuandong Liang<yl20e11@ecs.soton.ac.uk>.
.SH SEE ALSO
https://github.com/lyd-soton/cw1-6005-yl20e11

